update bekaert_db.cms_page b 
join test1.cms_page t on b.identifier = t.identifier 
set b.title = t.title,
 b.page_layout = t.page_layout,
 b.meta_keywords = t.meta_keywords,
 b.meta_description = t.meta_description,
 b.content_heading = t.content_heading,
 b.content = IF(@c1=REGEXP_SUBSTR(t.content, 'page_ids=".*?"'), 
 replace(
    replace(t.content, @c1,
 replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(@c1, "397","409"), "396", "410"),"395","371"),"394","408"),"393","407"),"421","394"),"456", "396"),"417","395"),"378","357"),"380","356"),"379","355"))
 , "qa-api.bekaert.cn", "api.bekaert.cn")
 , replace(t.content, "qa-api.bekaert.cn", "api.bekaert.cn")),
 b.creation_time = t.creation_time,
 b.update_time = t.update_time,
 b.is_active = t.is_active,
 b.sort_order = t.sort_order,
 b.layout_update_xml = t.layout_update_xml,
 b.custom_theme = t.custom_theme,
 b.custom_root_template = t.custom_root_template,
 b.custom_layout_update_xml = t.custom_layout_update_xml,
 b.layout_update_selected = t.layout_update_selected,
 b.custom_theme_from = t.custom_theme_from,
 b.custom_theme_to = t.custom_theme_to,
 b.meta_title = t.meta_title,
 b.website_root = t.website_root,
 b.created_in = t.created_in,
 b.updated_in = t.updated_in,
 b.top_banner_background_image = t.top_banner_background_image,
 b.cover_image = t.cover_image,
 b.cover_background_image = t.cover_background_image,
 b.cover_background_color = t.cover_background_color,
 b.subtitle = t.subtitle,
 b.short_description = t.short_description,
 b.is_include_search = t.is_include_search,
 b.is_excluded_from_search_result = t.is_excluded_from_search_result,
 b.content_text = t.content_text,
 b.page_header_render = t.page_header_render,
 b.news_date = t.news_date,
 b.news_type = t.news_type,
 b.display_mode = t.display_mode,
 b.news_sort_direction = t.news_sort_direction,
 b.news_redirect_url = t.news_redirect_url,
 b.grid_title = t.grid_title,
 b.grid_description = t.grid_description
where t.identifier in ("innovation","tire-tech-award","creativity-beyond-steel","our-core-competencies","engineering","research---development","steel-wire-transformation","coating-technologies","wire-rod","cold-rolling-steel","wire-drawing","thermal-treatment","cord-making","textile-technologies","metal-fiber-production-products","welding-mesh-production","profiling","hot-dip","electro-deposition","cladding","extrusion-of-polymers","lacquering","powder-coating","careers","the-hiring-process","digital-opportunities","graduates","why-join-us","preparation-tips","application-process","program-overview","working-in-production","operators","technicians","business-2023","news-20231015iblac","business-5-20230203newlogolaunch","business-5-20230516sustainabilityday","business-5-20230911yudaming","business-5-20230224sustainable","business-5-20230331cbscgreenplant","business-5-20230116acinjy","business-5","news-20230925","alupower-64d3265abef25","alupower","union-news-20230705actradeshow","union-news-20230622-655489cf3a79e","union-news-20230308womensdaycelebration","union-news-20230527bstcchildrensday","union-news-20230601bapbbscchildrenday","union-news-20230525bbscagilebuddygroup","union-news-20230610bbscsustainabilitydaywithchildren","news-20230427bapcampusvisit","news-20230915-steelrosenews","news-202306employeeclub","upcoming-exhibition-20230810","news-upcoming-exhibition-1","find-a-job");
